apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-application-set
spec:
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/glefer-itroom/gitops
              revision: main
              directories:
                - path: apps/*/overlays/*
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{path[1]}}-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/glefer-itroom/gitops
        targetRevision: main
        path: '{{path}}'
      destination:
        server: '{{server}}'
        namespace: guestbook
