apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-application-set
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/glefer-itroom/gitops
        targetRevision: main
        path: apps/*/overlays/{{name}}
      destination:
        server: '{{server}}'
        namespace: guestbook
