apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: symfony
    repo: "oci://harbor.tech.glefer.fr/helm/symfony"
    version: "0.0.1"
    releaseName: app1
    namespace: app1
    valuesInline:
      app.tag: 1.10.32