apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: mlflow-server
    repo: https://strangiato.github.io/helm-charts/
    version: "0.5.7"
    releaseName: mlflow-server
    namespace: my-namespace
    valuesFile: values.yaml
    valuesInline:
      fullnameOverride: helloagain